# Generated by Django 4.1.3 on 2024-06-17 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyRoomsdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkinstatus', models.BooleanField(default=False)),
                ('checkoutstatus', models.BooleanField(default=False)),
                ('checkIntime', models.TimeField()),
                ('checkottime', models.TimeField()),
                ('time', models.CharField(blank=True, choices=[('3hours', '3hours'), ('6hours', '6hours'), ('9hours', '9hours'), ('12hours', '12hours')], max_length=50)),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rooms')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
