# Generated by Django 4.1.3 on 2024-06-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hourlyroomsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gueststay',
            name='checkindate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gueststay',
            name='checkoutdate',
            field=models.DateTimeField(),
        ),
    ]
