# Generated by Django 4.1.3 on 2024-06-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_gueststay_checkindate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gueststay',
            name='adults',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gueststay',
            name='children',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gueststay',
            name='guestcity',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='gueststay',
            name='guestemail',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='gueststay',
            name='noofguest',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gueststay',
            name='purposeofvisit',
            field=models.CharField(blank=True, default=None, max_length=150),
        ),
    ]
