# Generated by Django 4.1.3 on 2024-06-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_gueststay_adults_alter_gueststay_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprofile',
            name='checkintime',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='checkouttime',
            field=models.TimeField(auto_now=True),
        ),
    ]
