# Generated by Django 4.1.3 on 2024-06-18 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_hotelprofile_checkintime_hotelprofile_checkouttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelprofile',
            name='checkintime',
        ),
        migrations.RemoveField(
            model_name='hotelprofile',
            name='checkouttime',
        ),
    ]
