# Generated by Django 4.1.3 on 2024-06-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_hotelprofile_checkintime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprofile',
            name='checkintimes',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='checkouttimes',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
