# Generated by Django 4.1.3 on 2024-06-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_hotelprofile_checkintimes_hotelprofile_checkouttimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelprofile',
            name='zipcode',
            field=models.CharField(max_length=50),
        ),
    ]
