# Generated by Django 4.1.3 on 2024-06-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_hotelprofile_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='taxtype',
            field=models.CharField(choices=[('GST', 'GST'), ('IGST', 'IGST')], default='IGST', max_length=5),
            preserve_default=False,
        ),
    ]
