# Generated by Django 4.1.3 on 2024-06-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_invoice_taxtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbookguest',
            name='taxtype',
            field=models.CharField(choices=[('GST', 'GST'), ('IGST', 'IGST')], default='GST', max_length=5),
            preserve_default=False,
        ),
    ]
