# Generated by Django 4.1.3 on 2024-06-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_eventbookguest_taxtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='working_hours',
            field=models.IntegerField(default=0),
        ),
    ]
