# Generated by Django 4.1.3 on 2024-06-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_eventbookguest_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbookguest',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
