# Generated by Django 4.1.3 on 2024-06-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_eventbookguest_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbookguest',
            name='Grand_total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
