# Generated by Django 4.1.3 on 2024-06-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_invoice_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercredit',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
