# Generated by Django 4.1.3 on 2024-06-25 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_customercredit_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercredit',
            name='phone',
            field=models.BigIntegerField(blank=True, default=9179335911, validators=[django.core.validators.MaxValueValidator(9999999999)]),
            preserve_default=False,
        ),
    ]
