# Generated by Django 4.1.3 on 2024-06-25 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_customercredit_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercredit',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.invoice'),
        ),
    ]
