# Generated by Django 4.1.3 on 2024-06-25 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_customercredit_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewqr',
            name='room_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.rooms'),
        ),
    ]
