# Generated by Django 4.1.3 on 2024-06-29 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_reviewqr_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreguestdata',
            name='another_guest_address',
            field=models.CharField(blank=True, default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='moreguestdata',
            name='another_guest_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='moreguestdata',
            name='another_guest_phone',
            field=models.BigIntegerField(blank=True, default=None, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
