# Generated by Django 4.1.3 on 2024-07-02 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_moreguestdata_another_guest_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freedemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone', models.BigIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('businessname', models.CharField(max_length=300)),
            ],
        ),
    ]
