# Generated by Django 4.1.3 on 2024-07-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_freedemo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymanagement',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailymanagement',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
