# Generated by Django 4.1.3 on 2024-07-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_marketiteams'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketiteams',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='marketproducts'),
        ),
    ]
